const router = require('express').Router();



module.exports = function (mongodb, mail, credentials, queries){
    router.get("/login", credentials.login);
    router.get("/signup", credentials.signup);
    router.get("/logout", credentials.logout);
    router.get("/getPlayers", queries.getPlayers);
    router.get("/getHostedTeams", queries.getHostedTeams);
    router.get("/getTeams", queries.getTeams);
    router.get("/getGlobalTeams", queries.getGlobalTeams);
    router.get("/getNextPlayers", queries.getNextPlayers);
    router.get("/getAllRecipients", queries.getAllRecipients);
    router.get("/chooseRole", queries.chooseRole);
    router.get("/modifyEvent", queries.modifyEvent);
    router.get("/getPresence", queries.getPresence);
    router.get("/getAbsence", queries.getAbsence);
    router.get("/getMaybe", queries.getMaybe);
    router.get("/getPlayerInformation", queries.getPlayerInformationQuery);
    router.get("/savePublicInfo", queries.savePublicInfo);
    router.get("/getPublicInfo", queries.getPublicInfo);
    router.get("/deleteEvents", queries.deleteEvents);
    router.get("/getUserInformation", queries.getUserInformationQuery);
    router.get("/getGeneralTeamInfo", queries.getGeneralTeamInfo);
    router.get("/getUpcommingEvents", queries.getUpcommingEvents);
    router.get("/changePresence", queries.changePresence);
    router.get("/joinTeam", queries.joinTeam);
    router.get("/createEvent", queries.createEvent);
    router.get("/getNextEvents", queries.getNextEvents);
    router.get("/getNextPastEvents", queries.getNextPastEvents);
    router.get("/createConversation", queries.createConversation);
    router.get("/getConversations", queries.getConversations);
    router.get("/getConversation", queries.getConversation);
    router.get("/quitTeam", queries.quitTeam);
    router.get("/excludeParticipant", queries.excludeParticipant);
    router.get("/joinPending", queries.joinPending);
    router.get("/generateNewInviteCode", queries.generateNewInviteCode);
    router.get("/getPendingList", queries.getPendingList);
    router.get("/acceptCoachFromPendingList", queries.acceptCoachFromPendingList);
    router.get("/refuseCoachFromPendingList", queries.refuseCoachFromPendingList);
    router.get("/resetEmail", queries.resetEmail);
    router.get("/confirmEmail", queries.confirmEmail);
    router.get("/loadBulkMessages", queries.loadBulkMessages);
    router.get("/getAccountInfo", queries.getAccountInfo);
    router.get("/modifyPassword", queries.modifyPassword);
    router.get("/getPlayerPublicInfo", queries.getPlayerPublicInfo);
    router.get("/setAccountInfo", queries.setAccountInfo);
    router.get("/resetPassword", queries.resetPassword);
    router.get("/changeTitle", queries.changeTitle);
    router.get("/getParticipantsList", queries.getParticipantsList);
    router.post("/saveTeamInfo", queries.saveTeamInfo);
    router.post("/newPlayer", queries.createPlayer);
    router.post("/sendFile", queries.sendFile);
    router.post("/newTeam", queries.createTeam);
    router.post("/savePlayerInfo", queries.savePlayerInfo);
    return router;
};